###
### Client config: IP-Adress and port of the NodePKI server
###

server:
    ip: 127.0.0.1
    port: 8081

applicant: "John Doe"

csr_defaults:
    country: "CY"
    state: "Cyberstate"
    locality: "Cybertown"
    organization: "Cyber Inc."

cert_lifetime_default: 365
