###
### Hostnames and ports of the NodePKI server
###

server:
    api:
        hostname: ca.adito.local
        port: 8081
    public:
        hostname: ca.adito.local
        port: 8080


###
### Username and password to authenticate with
###

user:
    username: api_username
    password: api_password


###
### CSR default values
###

csr_defaults:
    country: "DE"
    state: "Germany"
    locality: "Geisenhausen"
    organization: "ADITO Software GmbH"


###
### Default certificate lifetime
###

cert_lifetime_default: 365
