###
### Client config: IP-Adress and port of the NodePKI server
###

server:
    api:
        hostname: ca.adito.local
        port: 8081
    public:
        hostname: ca.adito.local
        port: 8080

applicant: "John Doe"

csr_defaults:
    country: "CY"
    state: "Cyberstate"
    locality: "Cybertown"
    organization: "Cyber Inc."

cert_lifetime_default: 365
