###
### Hostnames and ports of the NodePKI server
###

server:
    hostname: ca.adito.local
    port_plain: 8080
    port_tls: 443
    tls: false


###
### Username and password to authenticate with
###

user:
    username: api_username
    password: api_password


###
### CSR default values
###

csr_defaults:
    country: "DE"
    state: "Germany"
    locality: "Geisenhausen"
    organization: "ADITO Software GmbH"


###
### Default certificate lifetime
###

cert_lifetime_default: 365
